#!/bin/sh

. ./config

./unsplit-passphrase

mkdir -p "$GPGHOMEDIR"
chmod 700 "$GPGHOMEDIR"

gpg --decrypt --no-use-agent --passphrase-file "$passphrase" "$seckey_e" > "$seckey"
rm -f "$passphrase"
gpg --homedir "$GPGHOMEDIR" --import "$seckey"
rm -f "$seckey"

