#!/bin/sh

. ./config

mkdir -p "$partsdir"

$ssplit -x -t $nb_threshold -n $nb_shares < "$passphrase" > "$partsdir/all"

for num in `seq 1 $nb_shares`
do
    grep "^$num-" "$partsdir/all" > "$partsdir/$num"
done

rm -f "$partsdir/all"

